### PR TITLE
set user agent for amazon.cloud collection

### PR DESCRIPTION
**Pull request by abikouo**
##### SUMMARY

Replaces the original [pull request](https://github.com/ansible-collections/amazon_cloud_code_generator/pull/60/files) made from `ansible-collections/amazon_cloud_code_generator`

##### ISSUE TYPE

- Feature Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by alinabuzachis — APPROVED** [review]

**Comment by abikouo** [comment]
recheck

**Comment by alinabuzachis** [comment]
recheck

**Comment by abikouo** [comment]
recheck

**Comment by GomathiselviS** [comment]
vmware jobs are waiting on https://github.com/ansible-collections/vmware_rest_code_generator/pull/229 and https://github.com/ansible-collections/vmware.vmware_rest/pull/381

**Comment by GomathiselviS** [comment]
recheck

**Pull request merged**
