### PR TITLE
Add utility functions

### PR DESCRIPTION
**Pull request by GomathiselviS**
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1714

Signed-off-by: GomathiselviS <gomathiselvi@gmail.com>

##### SUMMARY

This PR moves a few functions from refresh_modules.py of amazon_cloud_code_generator and vmware_rest_code_generator to utils.py. 

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by goneri — APPROVED** [review]

**Comment by GomathiselviS** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by GomathiselviS** [comment]
regate

**Comment by GomathiselviS** [comment]
recheck

**Comment by goneri** [comment]
regate

**Pull request merged**
