### PR TITLE
Add requirements

### PR DESCRIPTION
**Pull request by alinabuzachis**
##### SUMMARY

tox.ini and fix linting issues

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by alinabuzachis** [comment]
@GomathiselviS units run fine locally, we should probably enable them in the CI.

**Comment by alinabuzachis** [comment]
shouldn't it look up for `refresh_modules` instead of `refresh-modules`? I guess the issue is coming from here https://github.com/ansible/ansible-zuul-jobs/pull/1736/files#diff-1651516334d52994025e65b62ea1ce5b2db20a48aa48e89b55c682049450e66eR747

```
2023-01-11 16:22:58.740868 \| controller \| using tox.ini: /workspace/src/github.com/ansible-collections/amazon.cloud/tox.ini (pid 169)
--
420 | 2023-01-11 16:22:58.764741 \| controller \| ERROR: unknown environment 'refresh-modules'


```

**Comment by GomathiselviS** [comment]
> shouldn't it look up for `refresh_modules` instead of `refresh-modules`? I guess the issue is coming from here https://github.com/ansible/ansible-zuul-jobs/pull/1736/files#diff-1651516334d52994025e65b62ea1ce5b2db20a48aa48e89b55c682049450e66eR747
> 
> ```
> 2023-01-11 16:22:58.740868 \| controller \| using tox.ini: /workspace/src/github.com/ansible-collections/amazon.cloud/tox.ini (pid 169)
> --
> 420 | 2023-01-11 16:22:58.764741 \| controller \| ERROR: unknown environment 'refresh-modules'
> ```

Fixing it [here](https://github.com/ansible/ansible-zuul-jobs/pull/1739)

**Comment by GomathiselviS** [comment]
> @GomathiselviS units run fine locally, we should probably enable them in the CI.

@alinabuzachis Unit tests run as part of cloud-tox-py3 job. Please let me know if you are talking about any other tests.

**Comment by alinabuzachis** [comment]
> > @GomathiselviS units run fine locally, we should probably enable them in the CI.
> 
> @alinabuzachis Unit tests run as part of cloud-tox-py3 job. Please let me know if you are talking about any other tests.

Oh, right, missed that job! Thanks.

**Comment by alinabuzachis** [comment]
recheck

**Review by GomathiselviS — APPROVED** [review]

**Comment by alinabuzachis** [comment]
recheck

**Pull request merged**
